import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

// Framer Motion Variants
const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.15 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 70 } },
};

export default function FAQPage() {
  return (
    <motion.div
      initial="hidden"
      animate="visible"
      variants={containerVariants}
      className="mt-8 flex h-[calc(100%-4rem)] flex-col justify-center space-y-8"
    >
      {/* Heading Section */}
      <motion.div variants={itemVariants} className="mb-8 space-y-4">
        <motion.h1
          className="text-6xl font-bold md:text-8xl"
          variants={itemVariants}
        >
          FAQs
        </motion.h1>
        <motion.div
          className="text-xs opacity-60 md:text-sm"
          variants={itemVariants}
        >
          <p>Frequently Asked Questions</p>
          <p>Here are some common questions about Quiz Bee with You</p>
        </motion.div>
      </motion.div>

      <Accordion type="single" collapsible className="w-full">
        {faqData.map(({ question, answer, value }) => (
          <AccordionItem key={value} value={value}>
            <AccordionTrigger asChild>
              <motion.div variants={itemVariants}>{question}</motion.div>
            </AccordionTrigger>
            <AccordionContent asChild>
              <div>{answer}</div>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </motion.div>
  );
}

// FAQ Data
const faqData = [
  {
    value: "item-1",
    question: "What is Quiz Bee with You?",
    answer:
      "Quiz Bee with You is a web-based platform that uses advanced Natural Language Processing and Question-Answering algorithms to generate quizzes automatically based on course lessons.",
  },
  {
    value: "item-2",
    question: "How does Quiz Bee with You generate quizzes?",
    answer:
      "The system analyzes your course content, identifies key points, and generates relevant questions by utilizing NLP and Question-Answering models to ensure high-quality and accurate quizzes.",
  },
  {
    value: "item-3",
    question: "Can I customize the questions generated by Quiz Bee with You?",
    answer:
      "Yes, after the system generates the quiz, you can review and modify the questions as needed before using them in assessments.",
  },
  {
    value: "item-4",
    question: "Is Quiz Bee with You suitable for all subjects?",
    answer:
      "Yes, Quiz Bee with You is designed to handle various subjects and topics, as long as the course material is provided in a readable format.",
  },
  {
    value: "item-5",
    question: "Is my data safe on Quiz Bee with You?",
    answer:
      "Absolutely! We prioritize your privacy and use encryption and secure data practices to protect your information.",
  },
  {
    value: "item-6",
    question: "Can I access Quiz Bee with You on any device?",
    answer:
      "Yes, the platform is fully responsive and can be accessed on desktops, tablets, and smartphones.",
  },
];
